// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var Main = function() {
	var _gthis = this;
	this.setVh();
	window.addEventListener("resize",this.debounce(function() {
		_gthis.setVh();
	},150));
	window.addEventListener("orientationchange",function(e) {
		_gthis.setVh();
	});
};
Main.main = function() {
	new Main();
};
Main.prototype = {
	setVh: function(e) {
		var vh = window.innerHeight * 0.01;
		window.document.documentElement.style.setProperty("--vh","" + vh + "px");
	}
	,debounce: function(callback,wait) {
		var timeout = null;
		return function(e) {
			if(timeout != null) {
				window.clearTimeout(timeout);
			}
			timeout = window.setTimeout(function() {
				callback();
			},wait);
		};
	}
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
